In [2]:
import tensorflow as tf

## constant

In [3]:
scalar = tf.constant(42)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])

In [4]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
tensor=tf.constant([[1, 2], [3, 4]])
# dimensions 
tensor_shape = tf.shape(tensor)
print(tensor_shape)

# How many dimensions are in the tensor? :rank
tensor_rank = tf.rank(tensor)
print(tensor_rank)
# elements 
tensor_size = tf.size(tensor)
print(tensor_size)

tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [6]:
x.numpy()

array([[4.]], dtype=float32)

In [7]:
y=tf.constant(12)
print(y)

tf.Tensor(12, shape=(), dtype=int32)


In [8]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(2,3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
#datatype change
dc_x=tf.cast(x,dtype=tf.float32)
print(dc_x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


## operators

In [10]:
# for square root it should be float type.
a=tf.constant([2],dtype=tf.float32)
print(tf.sqrt(a))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [11]:
a=tf.constant([1,2,3])
b=tf.constant([9,8,7])
res=tf.add(a,b)
res

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [12]:
res=a+b
res

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [13]:
tf.subtract(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [14]:
tf.multiply(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [15]:
tf.divide(a,b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [16]:
tf.pow(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([   1,  256, 2187], dtype=int32)>

In [17]:
a_cast=tf.cast(a,dtype=tf.float32)
tf.exp(a_cast)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)>

In [18]:
tf.sqrt(a_cast)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

In [19]:
a=tf.constant([[1,2],[4,5]])
b=tf.constant([[1,2],[4,5]])
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]], dtype=int32)>

## indexing


In [20]:
print(a[:])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [21]:
a[1:]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 5]], dtype=int32)>

In [22]:
a[1:2]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 5]], dtype=int32)>

In [23]:
a[::-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2]], dtype=int32)>

## reshape

In [24]:
x=tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [25]:
tf.reshape(x,(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [26]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
x_transposed = tf.transpose(x, perm=[1, 0])
print(x_transposed)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## Variables - trainable

In [27]:
v=tf.Variable(1.0)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [28]:
v.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [29]:
v.assign_add(3)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=5.0>

In [30]:
v.assign_sub(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=3.0>

In [31]:

def simple_function(x):
    return x**2

loss = simple_function(v)


In [32]:
with tf.GradientTape() as tape:
   
    loss = simple_function(v)

# Compute gradients
gradients = tape.gradient(loss, [v])


print("Gradients with respect to v:", gradients)


Gradients with respect to v: [<tf.Tensor: shape=(), dtype=float32, numpy=6.0>]


In [40]:

a=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
b=tf.constant([[1,2,3],[4,5,6]],dtype=tf.float32)
result=tf.square(a)
result.numpy()

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)